# TUGAS 1

In [12]:
#import library
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import statistics as st
from scipy import stats

url="https://raw.githubusercontent.com/077nabila/dataset/main/supermarket_sales%20-%20Sheet1.csv"

n=pd.read_csv(url)
n

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,C,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,1/29/2019,13:46,Ewallet,40.35,4.761905,2.0175,6.2
996,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,3/2/2019,17:16,Ewallet,973.80,4.761905,48.6900,4.4
997,727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2/9/2019,13:22,Cash,31.84,4.761905,1.5920,7.7
998,347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,2/22/2019,15:33,Cash,65.82,4.761905,3.2910,4.1
999,849-09-3807,A,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2/18/2019,13:28,Cash,618.38,4.761905,30.9190,6.6

In [13]:
# Show dataset shape
number_of_columns = n.shape[1]

In [14]:
# Show all columns for dataset
pd.set_option('display.max_columns', number_of_columns)
pd.set_option('display.max_rows', number_of_columns)

In [15]:
# Show all columns from dataframe
n.columns

Index(['Invoice ID', 'Branch', 'City', 'Customer type', 'Gender',
       'Product line', 'Unit price', 'Quantity', 'Tax 5%', 'Total', 'Date',
       'Time', 'Payment', 'cogs', 'gross margin percentage', 'gross income',
       'Rating'],
      dtype='object')

In [22]:
n[["Invoice ID","City", "Gender"]].head(5)

    Invoice ID       City  Gender
0  750-67-8428     Yangon  Female
1  226-31-3081  Naypyitaw  Female
2  631-41-3108     Yangon    Male
3  123-19-1176     Yangon    Male
4  373-73-7910     Yangon    Male

In [23]:
# embark code
code_embark_for_cherbourg = "Femele"
code_embark_for_southampton = "Male"

# binary value
value_of_one = 1
value_of_zero = 0

def change_code_embark_to_biner(Gender):
    return value_of_one if Gender == code_embark_for_southampton else value_of_zero

In [24]:
# Update all values of 'Gender' series
n["Gender"] = n["Gender"].apply(change_code_embark_to_biner)

In [25]:
n[["Invoice ID","City", "Gender"]].head(5)

    Invoice ID       City  Gender
0  750-67-8428     Yangon       0
1  226-31-3081  Naypyitaw       0
2  631-41-3108     Yangon       1
3  123-19-1176     Yangon       1
4  373-73-7910     Yangon       1

In [26]:
# CONSTAN VARIABLE
DECREMENT_BY_ONE = 1
INCREMENT_BY_ONE = 1

CONTINGENCY_TABLE_VALUE = {
    "q" : (1,1),
    "r" : (1,0),
    "s" : (0,1),
    "t" : (0,0),
}

In [28]:
def get_series(n, idx, series):
    return n.loc[(idx), series]

In [29]:
def get_dissimilarity_dataset(n, series_index = [], series = []):
    first_series = get_series(n, series_index[0], series)
    second_series = get_series(n, series_index[1], series)
    dataset = pd.concat([first_series,second_series],axis=1)
    return dataset.T

In [30]:
get_dissimilarity_dataset(n, [1,2], ["Invoice ID","City"]).T

                      1            2
Invoice ID  226-31-3081  631-41-3108
City          Naypyitaw       Yangon

In [32]:
n.loc[0:5, ["City", "Gender"]]

        City  Gender
0     Yangon       0
1  Naypyitaw       0
2     Yangon       1
3     Yangon       1
4     Yangon       1
5  Naypyitaw       1

In [33]:
def count_contingency_value(n, start_index = 0, last_index = 1):

    CONTINGENCY_VALUE = {
        "q" : 0,
        "r" : 0,
        "s" : 0,
        "t" : 0,
    }

    column_range = n.shape[1]

    for column in range(column_range):
        for value in CONTINGENCY_TABLE_VALUE:
            item = list((tuple(n.loc[(start_index):(last_index), n.columns[column]]) == CONTINGENCY_TABLE_VALUE[value], value))
            if item[0] == True:
                if item[1] == "q":
                    CONTINGENCY_VALUE["q"] += 1
                if item[1] == "r":
                    CONTINGENCY_VALUE["r"] += 1
                if item[1] == "s":
                    CONTINGENCY_VALUE["s"] += 1
                if item[1] == "t":
                    CONTINGENCY_VALUE["t"] += 1

    return CONTINGENCY_VALUE

In [34]:
# d(1,2)
d_1_2 = get_dissimilarity_dataset(n, [1,2], ["City", "Gender"])

In [35]:
d_e_1_2 = count_contingency_value(d_1_2, 1, 2)

In [37]:
# d(1,3)
d_1_3 = get_dissimilarity_dataset(n, [1,3], ["City", "Gender"])

In [38]:
d_e_1_3 = count_contingency_value(d_1_3, 1, 3)

In [40]:
# d(1,4)
d_1_4 = get_dissimilarity_dataset(n, [1,4], ["City", "Gender"])

In [41]:
d_e_1_4 = count_contingency_value(d_1_4, 1, 4)

In [42]:
# d(1,5)
d_1_5 = get_dissimilarity_dataset(n, [1,5], ["City", "Gender"])

In [43]:
d_e_1_5 = count_contingency_value(d_1_5, 1, 5)

jarak

In [44]:
def measure_dissimilarity_binary_value_assymetric_distance(contingency_value):

    return (contingency_value["r"] + contingency_value["s"]) / (contingency_value["q"] + contingency_value["r"] + contingency_value["s"])

In [45]:
d_1_2 = measure_dissimilarity_binary_value_assymetric_distance(d_e_1_2)
d_1_3 = measure_dissimilarity_binary_value_assymetric_distance(d_e_1_2)
d_1_4 = measure_dissimilarity_binary_value_assymetric_distance(d_e_1_2)

In [46]:
d_1_2

1.0

In [47]:
d_1_3

1.0

In [48]:
1.0

1.0

In [49]:
d_1_4

1.0

In [50]:
1.0

1.0